### ISSUE TITLE
cURL error 6: Could not resolve host: https (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by Thiyagarajantender** [swordfox/silverstripe-shopify#2]
cURL error 6: Could not resolve host: https (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by swordfox** [comment]
Hey,

Have you set up your base URI correctly in the config?

`shopify_domain: 'YOUR_SHOPIFY_DOMAIN' # mydomain.myshopify.com`

Cheers
